# Generated by Django 4.2 on 2023-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.CharField(max_length=40, verbose_name='Date Posted')),
                ('media_type', models.CharField(max_length=40, verbose_name='Media type')),
                ('text_data', models.TextField(verbose_name='Post Description')),
                ('likes', models.IntegerField(verbose_name='Total Likes of Post')),
                ('comments', models.IntegerField(verbose_name='Total Comments of Comment')),
                ('views', models.CharField(max_length=40, verbose_name='Post Views')),
                ('media_link', models.TextField(verbose_name='Media Links')),
            ],
        ),
    ]
