# Generated by Django 4.2 on 2023-04-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinpost',
            old_name='text_data',
            new_name='post_data',
        ),
    ]
