# Generated by Django 4.2 on 2023-04-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0002_rename_text_data_linkedinpost_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='company_name',
            field=models.CharField(default='tecblic', max_length=50, verbose_name='Company Name'),
            preserve_default=False,
        ),
    ]
