# Generated by Django 4.2 on 2023-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0003_linkedinpost_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_urls', models.CharField(max_length=150, verbose_name='Company Urls')),
            ],
        ),
    ]
