# Generated by Django 4.2 on 2023-04-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0004_company_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_list',
            new_name='CompanyList',
        ),
    ]
