# Generated by Django 3.2.16 on 2023-04-18 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0005_rename_company_list_companylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='date_on_create',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 7, 33, 12, 614634), verbose_name='Date on Create'),
        ),
    ]
