# Generated by Django 3.2.16 on 2023-04-18 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0006_companylist_date_on_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylist',
            name='date_on_create',
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='date_on_create',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 7, 34, 31, 330342), verbose_name='Date on Create'),
        ),
    ]
